---
title: Booker T. Washington High School Class of 2007
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: true
  uploads:
    title: Uploads
    output: true
email: bookertwhs.2007@gmail.com
description: Booker T. Washington Class of 2007. Information regarding reunions, meetups,
  and going ons of our class.
baseurl: ''
url: ''
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
sass:
  sass_dir: _scss
